# These are supported funding model platforms

github: [ncnoman]
ko_fi: # Your Ko-fi username once you set one up
# buy_me_a_coffee: # Your Buy Me a Coffee username
# custom: ['https://your-link.com']
